=== saturnairjam/PortfolioVisualizer/Data/Schemas/AssetClassSchema.json
{
    "$schema": "http://json-schema.org/schema#",
    "title": "Asset Class Schema",
    "type": "object",
    "additionalProperties": false,
    "properties":
    {
        "Name":
        {
            "description": "asset class name",
            "type": "string"
        },
        "StartYear":
        {
            "description": "start year of NAV array's first entry",
            "type": "integer",
            "minimum": 0
        },
        "StartMonth":
        {
            "description": "start month of NAV array's first entry",
            "type": "integer",
            "minimum": 1,
            "maximum": 12
        },
        "Currency":
        {
            "description": "currency in which net asset values are expressed",
            "type": "string",
            "enum": ["INR", "USD"]
        },
        "NetAssetValueArray":
        {
            "description": "net asset value array",
            "type": "array",
            "items":
            {
                "type": "number"
            }
        }
    },
    "required":
    [
        "Name",
        "StartYear",
        "StartMonth",
        "Currency",
        "NetAssetValueArray"
    ]
}

=== saturnairjam/PortfolioVisualizer/Data/AssetClasses/Nifty50TotalReturnsIndex.json
{
    "Name": "NIFTY 50 Total Returns Index",
    "StartYear": 1999,
    "StartMonth": 6,
    "Currency": "INR",
    "NetAssetValueArray":
    [
        1256.38,
        1386.99,
        1496.66,
        1497.9,
        1405.03,
        1459.09,
        1562.92,
        1639.66,
        1755.45,
        1623.5,
        1502.41,
        1474.94,
        1573.55,
        1426.26,
        1492.45,
        1362.52,
        1256.62,
        1358.92,
        1354.05,
        1470.01,
        1448.26,
        1230.49,
        1207.72,
        1256.58,
        1193.8,
        1159.68,
        1141.48,
        991.77,
        1055.47,
        1159.08,
        1150.28,
        1168.1,
        1242.55,
        1228.95,
        1181.82,
        1122.86,
        1155.86,
        1054.4,
        1115.02,
        1063.92,
        1053.44,
        1162.91,
        1211.66,
        1154.67,
        1178.72,
        1084.64,
        1038,
        1122.32,
        1272.21,
        1337.86,
        1538.08,
        1610.21,
        1770.08,
        1837.98,
        2139.93,
        2062.42,
        2052.4,
        2020.25,
        2048.22,
        1698.16,
        1727.93,
        1878.62,
        1882.09,
        2020.62,
        2069.39,
        2268.99,
        2418.88,
        2393.76,
        2447.94,
        2369.69,
        2214.96,
        2433.73,
        2599.93,
        2711.24,
        2801.99,
        3066.15,
        2795.89,
        3127.8,
        3353.37,
        3549.92,
        3639.43,
        4028.82,
        4213.88,
        3642.31,
        3721.71,
        3745.46,
        4073.55,
        4288.97,
        4476.5,
        4729.13,
        4758.45,
        4899.39,
        4504.73,
        4605.89,
        4934.46,
        5185.95,
        5223.82,
        5483.25,
        5411.29,
        6094.11,
        7163.3,
        6997.6,
        7461.48,
        6245.45,
        6356.92,
        5762.88,
        6289.07,
        5937.81,
        4929.98,
        5297.47,
        5337.28,
        4807.2,
        3539.57,
        3379.53,
        3635.87,
        3538.57,
        3403.33,
        3720.51,
        4278.54,
        5480.11,
        5296.58,
        5737.09,
        5774.96,
        6302.19,
        5846.03,
        6245.49,
        6456.97,
        6061.68,
        6114.27,
        6521.55,
        6559.98,
        6330.54,
        6636.89,
        6712.14,
        6762.76,
        7554.94,
        7546.4,
        7353.36,
        7698.29,
        6910.76,
        6696.09,
        7327.83,
        7224.51,
        6997.07,
        7133.6,
        6934.57,
        6334.48,
        6265.26,
        6755.07,
        6128.97,
        5865.49,
        6600.95,
        6838.32,
        6728.46,
        6668.4,
        6275.4,
        6752.88,
        6700.96,
        6747.3,
        7321.57,
        7217.67,
        7556.73,
        7591.99,
        7759.87,
        7322.68,
        7315.35,
        7634.29,
        7734.03,
        7563.28,
        7449.52,
        7103.56,
        7454.82,
        8194.06,
        8035.27,
        8204.85,
        7930.34,
        8178.01,
        8739.91,
        8730.05,
        9437.81,
        9966.14,
        10140.34,
        10456.85,
        10475.04,
        10952.14,
        11303.65,
        10904.18,
        11598.64,
        11723.28,
        11201.99,
        10794.27,
        11135.85,
        11085.87,
        11328.56,
        10588.8,
        10566.29,
        10732.25,
        10560.84,
        10575.63,
        10068.86,
        9304.26,
        10325.5,
        10474.15,
        10908.07,
        11121.39,
        11614.8,
        11826.19,
        11598.22,
        11628.32,
        11092.59,
        11040.41,
        11548.15,
        11990.44,
        12406.69,
        12582.88,
        13018.69,
        12932.33,
        13724.19,
        13521.03,
        13351.99,
        14108.55,
        13966.58,
        14381.92,
        15065.82,
        14358.71,
        13865.57,
        14723.32,
        14750.26,
        14753.91,
        15672.47,
        16143.51,
        15114.08,
        14377.38,
        15059.37,
        15048.98,
        15012.34,
        14979.39,
        16146.11,
        16318.66,
        16583.46,
        16433.85,
        15539.43,
        15440.47,
        16072.5,
        16667.29,
        16917.89,
        17077.06,
        16790.45,
        15726.92,
        12105.66,
        13884.18,
        13503.45,
        14527.18,
        15645.34,
        16110.07,
        15916.72,
        16504.16,
        18392.54
    ]
}

=== saturnairjam/PortfolioVisualizer/Data/AssetClasses/GoldPricePerTroyOz.json
{
    "Name": "Gold Price Per Troy Oz",
    "StartYear": 1979,
    "StartMonth": 1,
    "Currency": "INR",
    "NetAssetValueArray":
    [
        1840.8,
        2011.7,
        1940.2,
        2013.1,
        2253.4,
        2190.6,
        2354.1,
        2527.7,
        3190.3,
        3142.6,
        3310.3,
        4189.6,
        5329.6,
        5138.1,
        4155.4,
        4155.2,
        4152.3,
        5150.4,
        4813.2,
        4903.6,
        5211.3,
        4911.2,
        4871.9,
        4620.3,
        4123.2,
        4082.9,
        4240.5,
        3998.5,
        4046.5,
        3703.8,
        3655.1,
        3820.1,
        3870.4,
        3876.4,
        3815.0,
        3625.1,
        3546.0,
        3373.9,
        2987.6,
        3322.1,
        3072.3,
        2971.9,
        3265.4,
        3933.3,
        3824.8,
        4108.4,
        4127.6,
        4320.0,
        5003.5,
        4197.0,
        4104.3,
        4286.4,
        4391.8,
        4183.6,
        4291.0,
        4219.7,
        4123.3,
        3923.5,
        4218.6,
        3995.0,
        4002.4,
        4220.1,
        4169.1,
        4094.2,
        4218.3,
        4178.2,
        3919.9,
        4007.9,
        4140.0,
        4017.0,
        4016.0,
        3825.9,
        3834.8,
        3783.1,
        4001.6,
        3994.6,
        3857.0,
        3874.7,
        3901.3,
        3974.0,
        3826.2,
        3899.9,
        3861.2,
        3920.6,
        4329.0,
        4172.4,
        4172.5,
        4206.1,
        4364.7,
        4276.4,
        4468.9,
        4778.8,
        5376.9,
        5187.4,
        5069.3,
        5061.0,
        5264.7,
        5202.4,
        5419.5,
        5734.5,
        5758.3,
        5727.8,
        5938.2,
        5870.5,
        5954.3,
        6078.5,
        6230.4,
        6116.9,
        6056.5,
        5501.9,
        6171.1,
        5900.7,
        6119.1,
        6143.3,
        6290.8,
        6120.7,
        5773.7,
        6296.2,
        6256.7,
        6123.1,
        5970.3,
        5884.4,
        5942.8,
        5922.9,
        5869.4,
        6142.9,
        6011.3,
        5962.5,
        6115.9,
        6309.7,
        6881.8,
        6624.8,
        7041.0,
        6957.4,
        6334.4,
        6379.3,
        6295.5,
        6140.5,
        6457.2,
        6783.8,
        7333.1,
        6895.0,
        6999.6,
        6948.9,
        6810.6,
        6917.0,
        6942.2,
        7226.6,
        7527.3,
        7785.6,
        9348.0,
        8953.7,
        9120.5,
        9241.4,
        9466.7,
        9080.6,
        9182.9,
        9210.3,
        9913.3,
        9615.7,
        9669.2,
        9838.5,
        10174.5,
        9700.0,
        9903.8,
        9632.5,
        9425.6,
        9639.3,
        9642.4,
        9885.6,
        10539.9,
        11114.5,
        11780.3,
        11869.9,
        12585.5,
        11702.3,
        11159.0,
        11602.7,
        11630.4,
        12252.6,
        11853.7,
        11967.3,
        12209.6,
        11808.3,
        12159.4,
        12085.7,
        12046.5,
        12100.5,
        12383.2,
        12044.2,
        12027.8,
        12022.1,
        11762.5,
        11828.8,
        12314.7,
        12250.8,
        12076.6,
        12153.4,
        12042.9,
        12179.8,
        13027.2,
        13086.6,
        13532.3,
        13608.9,
        14776.2,
        13892.5,
        13515.5,
        13597.7,
        13681.0,
        13457.9,
        13697.4,
        13784.7,
        13511.3,
        13510.2,
        13262.8,
        13228.4,
        12394.8,
        12866.6,
        12489.9,
        12162.1,
        12363.8,
        11976.9,
        11649.1,
        11820.0,
        12012.1,
        11324.1,
        11452.0,
        11378.7,
        11834.3,
        11702.7,
        11884.2,
        12339.5,
        12235.8,
        12555.7,
        12287.7,
        11625.0,
        12460.1,
        12381.8,
        12548.3,
        12230.4,
        12130.9,
        12249.9,
        11857.1,
        12260.7,
        11509.5,
        11317.3,
        11070.0,
        11075.5,
        13034.9,
        12977.9,
        12649.7,
        12631.0,
        12360.0,
        12806.5,
        12067.7,
        12008.0,
        12135.8,
        12872.4,
        12459.3,
        12678.3,
        12597.5,
        12387.9,
        12608.7,
        12811.3,
        12271.5,
        12416.2,
        12015.3,
        12323.3,
        12575.2,
        12729.0,
        12531.9,
        12869.2,
        14024.8,
        13377.2,
        13204.7,
        13332.8,
        13694.4,
        14465.5,
        14702.3,
        15080.2,
        16006.7,
        15561.9,
        14818.2,
        15161.4,
        15650.9,
        15318.9,
        15413.3,
        16648.2,
        17567.8,
        16561.2,
        15892.0,
        15943.4,
        16993.0,
        16078.6,
        16368.9,
        17217.5,
        17754.9,
        17504.9,
        18232.5,
        18991.4,
        18106.7,
        17906.3,
        18397.1,
        17276.6,
        17849.6,
        18196.9,
        18151.2,
        18874.0,
        19119.9,
        19305.1,
        20171.8,
        18935.5,
        18429.0,
        18985.6,
        18666.8,
        18966.0,
        18130.1,
        19005.1,
        18635.8,
        19102.0,
        20806.4,
        21233.2,
        22750.3,
        23090.1,
        25096.1,
        24669.7,
        25936.8,
        28925.3,
        30233.9,
        28245.5,
        29449.2,
        29014.6,
        27520.6,
        27186.9,
        28928.2,
        27972.3,
        28727.4,
        29407.5,
        28763.0,
        27885.6,
        26762.8,
        26493.2,
        26874.6,
        27468.0,
        29606.7,
        31045.9,
        31046.2,
        32862.3,
        36353.0,
        38874.6,
        37452.0,
        35288.6,
        37604.5,
        40024.0,
        39083.9,
        36597.9,
        41540.5,
        36135.6,
        40794.2,
        42374.2,
        44945.2,
        48685.3,
        46498.6,
        44193.4,
        45960.7,
        44767.2,
        45025.1,
        46652.3,
        47900.6,
        48843.6,
        54690.0,
        50606.8,
        49794.3,
        51095.9,
        50080.4,
        52311.5,
        55985.7,
        57777.6,
        54247.4,
        58611.8,
        58730.0,
        59829.4,
        63481.9,
        62846.9,
        60922.6,
        63868.9,
        64172.2,
        67892.1,
        69211.6,
        67299.6,
        71963.4,
        83511.7,
        79339.5,
        83852.8,
        91149.9,
        81303.8,
        86232.1,
        86747.7,
        84696.1,
        87020.9,
        87493.4,
        89252.2,
        90207.5,
        91697.8,
        93675.1,
        92473.6,
        93885.8,
        90814.4,
        88548.0,
        86422.3,
        86864.9,
        79142.4,
        78768.3,
        70834.6,
        79928.2,
        92151.1,
        83045.5,
        81366.4,
        78300.0,
        74504.3,
        78381.4,
        82216.5,
        77146.5,
        77715.9,
        73892.0,
        79090.7,
        77786.5,
        78019.3,
        75131.0,
        71484.9,
        73395.5,
        76125.7,
        78053.6,
        75031.3,
        74283.9,
        74963.6,
        76090.2,
        74569.3,
        70427.4,
        75449.1,
        73123.0,
        74646.8,
        70780.9,
        70125.6,
        75466.2,
        84498.0,
        81917.2,
        85277.1,
        81556.1,
        89144.0,
        89893.9,
        87680.5,
        88052.0,
        84952.4,
        80639.7,
        77772.2,
        82282.4,
        83772.1,
        80834.3,
        81470.7,
        81695.2,
        80295.9,
        81314.9,
        83855.2,
        83812.1,
        82269.2,
        82547.3,
        82401.3,
        85550.2,
        85853.0,
        86343.7,
        87643.0,
        88088.3,
        85674.6,
        83740.4,
        85285.3,
        86063.7,
        89839.5,
        84857.1,
        89293.4,
        94109.5,
        93826.2,
        89738.8,
        89188.8,
        90288.5,
        97259.7,
        98194.0,
        109139.2,
        105261.4,
        107169.8,
        104747.5,
        108120.0,
        113044.6,
        116178.9,
        121719.1,
        127868.0,
        130717.8,
        133498.2,
        146999.1,
        144075.6,
        139215.5,
        139459.2,
        130527.8
    ]
}

=== saturnairjam/PortfolioVisualizer/Data/AssetClasses/Nasdaq100TotalReturnsIndex.json
{
    "Name": "NASDAQ 100 Total Returns Index",
    "StartYear": 1999,
    "StartMonth": 4,
    "Currency": "USD",
    "NetAssetValueArray":
    [
        2136.7,
        2090.2,
        2297.4,
        2271.7,
        2397.8,
        2408.9,
        2638.6,
        2968.1,
        3710,
        3572.2,
        4269.7,
        4400.7,
        3775.8,
        3326.5,
        3766.5,
        3612.1,
        4080.8,
        3573.5,
        3285,
        2508.7,
        2343.8,
        2595.5,
        1910.3,
        1574.9,
        1857.2,
        1802,
        1169.9,
        1366.7,
        1598.4,
        1579.4,
        1552.5,
        1361.5,
        1455.2,
        1279.3,
        1210.5,
        1053.3,
        964,
        944.3,
        834.2,
        991.7,
        1118.6,
        986.7,
        985.5,
        1012.9,
        1021.9,
        1109.6,
        1202,
        1205.9,
        1281.5,
        1346.3,
        1308.7,
        1422.7,
        1430.9,
        1475,
        1500.4,
        1478.1,
        1446,
        1408.9,
        1474.6,
        1525.4,
        1408.7,
        1377.7,
        1422.1,
        1496.7,
        1582.8,
        1633.5,
        1531.4,
        1524,
        1495.4,
        1433.3,
        1557.4,
        1507.9,
        1620.8,
        1598.3,
        1618.5,
        1596,
        1691.4,
        1664.5,
        1731,
        1691.6,
        1725.4,
        1722.6,
        1601.2,
        1597,
        1530.5,
        1603.3,
        1678.9,
        1758.6,
        1819.5,
        1785.7,
        1821.8,
        1792.2,
        1803.4,
        1900.7,
        1963.8,
        1969.9,
        1968.1,
        2027.7,
        2132.2,
        2283.1,
        2132.4,
        2129.2,
        1880.7,
        1784.2,
        1822.1,
        1961.1,
        2080.4,
        1880.5,
        1893.1,
        1918.7,
        1634.1,
        1368,
        1216.9,
        1244,
        1212,
        1148.9,
        1272.7,
        1435,
        1479.3,
        1522.6,
        1653,
        1677.3,
        1774.5,
        1721.4,
        1827,
        1923.4,
        1800.4,
        1883,
        2028,
        2072.6,
        1921.2,
        1804.7,
        1934.7,
        1836.6,
        2076.6,
        2208.6,
        2205.2,
        2310.8,
        2378,
        2452.4,
        2440.7,
        2509.3,
        2480,
        2431.7,
        2472.2,
        2348.9,
        2242.6,
        2475.4,
        2412.8,
        2395.4,
        2596.2,
        2764.3,
        2904.3,
        2872.4,
        2667.4,
        2765.2,
        2794.7,
        2938.4,
        2968.7,
        2809.9,
        2850.1,
        2835,
        2910.5,
        2924.8,
        3012.2,
        3087.4,
        3195.5,
        3121.1,
        3317.2,
        3307.8,
        3464.8,
        3638.5,
        3767.2,
        3881.6,
        3807.4,
        4004.1,
        3897.7,
        3884.7,
        4061.5,
        4186.9,
        4235.8,
        4451.8,
        4418.4,
        4538.3,
        4744.3,
        4634.7,
        4540.8,
        4869.8,
        4756.4,
        4846.1,
        4958.3,
        4839.4,
        5053.3,
        4716.6,
        4615.6,
        5134.5,
        5163,
        5086.6,
        4741.1,
        4665.4,
        4981.9,
        4826.4,
        5041.3,
        4925.2,
        5276.4,
        5333.3,
        5452.5,
        5371.5,
        5394.7,
        5456.6,
        5742.9,
        5993.8,
        6116.5,
        6285.2,
        6529,
        6372.5,
        6638.3,
        6773.3,
        6765.5,
        7073.4,
        7219.4,
        7256.9,
        7888.2,
        7792.3,
        7485.7,
        7516.4,
        7943.1,
        8029.9,
        8251.5,
        8746.9,
        8721.5,
        7969.8,
        7962.6,
        7259.6,
        7924.4,
        8157,
        8485.7,
        8952.1,
        8214,
        8846,
        9055,
        8886.5,
        8960,
        9351.6,
        9735.2,
        10124,
        10428.2,
        9825.9,
        9081.8,
        10465.2,
        11125.6,
        11604.9,
        12710.7,
        14129.2,
        13328,
        12906.7,
        14339.94
    ]
}

=== saturnairjam/PortfolioVisualizer/Data/AssetClasses/Crisil10YearGiltFund.json
{
    "Name": "CRISIL 10-year GILT Index",
    "StartYear": 2001,
    "StartMonth": 9,
    "Currency": "INR",
    "NetAssetValueArray":
    [
        1008.78,
        1034.86,
        1101.4,
        1103.02,
        1134.35,
        1137.94,
        1169.67,
        1175.68,
        1167.82,
        1193.69,
        1212.83,
        1228.62,
        1236.26,
        1263.4,
        1319.33,
        1339.85,
        1324.38,
        1368.1,
        1357.4,
        1385.05,
        1400.12,
        1413.33,
        1430.41,
        1471.91,
        1488.89,
        1503.13,
        1503.2,
        1512.85,
        1509.98,
        1513.21,
        1531.8,
        1541.82,
        1530.74,
        1477.62,
        1452.92,
        1466.2,
        1458.53,
        1403.45,
        1385.34,
        1440.45,
        1443.32,
        1466.88,
        1461.79,
        1401.21,
        1446.18,
        1463.79,
        1461.24,
        1460.06,
        1466.46,
        1476.99,
        1487.23,
        1492.45,
        1484.79,
        1482.14,
        1489.81,
        1516.24,
        1498.33,
        1459.43,
        1458.99,
        1502.84,
        1536.97,
        1547.82,
        1578.03,
        1568.18,
        1567.27,
        1549.69,
        1557.96,
        1551.44,
        1571.05,
        1575.01,
        1612.7,
        1613.98,
        1624.31,
        1641.38,
        1644.64,
        1667.74,
        1708.65,
        1713.69,
        1683.29,
        1699.04,
        1689.53,
        1636.05,
        1583.4,
        1657.51,
        1679.11,
        1813.95,
        1876.32,
        2127.73,
        2012.11,
        2007.66,
        1877.07,
        1996.27,
        1941.18,
        1909.39,
        1902.28,
        1855.03,
        1898.46,
        1896.41,
        1940.16,
        1943.44,
        1955.87,
        1930.24,
        1944.57,
        1932.01,
        1960.89,
        1974.89,
        1954.17,
        1950.05,
        1973.45,
        1952.78,
        1970.9,
        2003.8,
        1987.85,
        2017.75,
        2034.3,
        2008.93,
        1985.4,
        2010.16,
        2007.09,
        2038.91,
        2036.56,
        1995.11,
        2004.55,
        2042.15,
        2095.39,
        2118.74,
        2083.83,
        2085.76,
        2139.33,
        2153.43,
        2158.12,
        2173.27,
        2200.57,
        2206.03,
        2226.24,
        2260,
        2295.19,
        2315.96,
        2319.29,
        2366.39,
        2423.87,
        2414.32,
        2311.44,
        2262.53,
        2253.41,
        2290.2,
        2245.96,
        2244.68,
        2268.17,
        2271.18,
        2295.99,
        2309.02,
        2351.73,
        2353.76,
        2374.26,
        2383.57,
        2407.71,
        2461.02,
        2508.11,
        2562.14,
        2605.39,
        2616.27,
        2630.54,
        2627,
        2651.17,
        2630.66,
        2657.3,
        2678.08,
        2738.93,
        2737.95,
        2728.9,
        2751.44,
        2765.08,
        2791.6,
        2840.29,
        2862.08,
        2872.67,
        2894.62,
        2967.96,
        2995.9,
        3043.35,
        3068.53,
        3205.93,
        3163.38,
        3202.98,
        3121.72,
        3177.5,
        3137.77,
        3190.85,
        3233.13,
        3260.86,
        3264.57,
        3251.32,
        3225.57,
        3201.55,
        3161.92,
        3125.12,
        3076.35,
        3165.46,
        3106.85,
        3114.71,
        3119.01,
        3166.36,
        3149.16,
        3154.8,
        3210.51,
        3282.25,
        3352.46,
        3348.74,
        3346.28,
        3381.23,
        3386.17,
        3494.55,
        3550.39,
        3693.25,
        3664.75,
        3650.46,
        3683.55,
        3707.56,
        3703.24,
        3711.86,
        3791.88,
        3876.7,
        3901.36,
        3950.24,
        3947.16,
        3979.14,
        3906.97,
        3952.46,
        4011.04,
        4021.34
    ]
}
