=== saturnairjam/PortfolioVisualizer/Data/Schemas/PortfolioSchema.json
{
    "$schema": "http://json-schema.org/schema#",
    "title": "Portfolio Schema",
    "type": "object",
    "additionalProperties": false,
    "properties":
    {
        "Name":
        {
            "description": "portfolio name",
            "type": "string"
        },
        "AssetClassWeights":
        {
            "description": "list of asset classes & their (un-normalized) weights",
            "type": "array",
            "items":
            {
                "type": "array",
                "items":
                [
                    {
                        "type": "string"
                    },
                    {
                        "type": "integer",
                        "minimum": 0
                    }
                ]
            }
        },
        "RebalancingStrategy":
        {
            "type": "string",
            "enum": ["Threshold", "Periodic"]
        },
        "MonthsBetweenRebalancing":
        {
            "description": "the number of months between rebalancing (used as minimum for threshold-based rebalancing)",
            "type": "integer",
            "minimum": 1
        },
        "RebalancingThreshold":
        {
            "description": "the rebalancing threshold expressed as a percentage; ignored for periodic rebalancing",
            "type": "integer",
            "minimum": 0
        },
        "InflationAdjustedReturns":
        {
            "description": "whether calculated portfolio returns should be inflation-adjusted or not",
            "type": "boolean"
        }
    },
    "required":
    [
        "Name",
        "AssetClassWeights",
        "RebalancingStrategy",
        "MonthsBetweenRebalancing",
        "RebalancingThreshold",
        "InflationAdjustedReturns"
    ]
}

=== saturnairjam/PortfolioVisualizer/Data/Portfolios/PermanentPortfolio.json
{
    "Name": "Permanent Portfolio",
    "AssetClassWeights":
    [
        ["NIFTY 50 Total Returns Index", 25],
        ["CRISIL Liquid Fund Index", 25],
        ["CRISIL 10-year GILT Index", 25],
        ["Gold Price Per Troy Oz", 25]
    ],
    "RebalancingStrategy": "Periodic",
    "MonthsBetweenRebalancing": 12,
    "RebalancingThreshold": 0,
    "InflationAdjustedReturns": false
}

=== saturnairjam/PortfolioVisualizer/Data/Portfolios/GoldenButterflyPortfolio.json
{
    "Name": "Golden Butterfly Portfolio",
    "AssetClassWeights":
    [
        ["NIFTY 50 Total Returns Index", 20],
        ["CRISIL Liquid Fund Index", 20],
        ["CRISIL 10-year GILT Index", 20],
        ["Gold Price Per Troy Oz", 20],
        ["NASDAQ 100 Total Returns Index", 20]
    ],
    "RebalancingStrategy": "Periodic",
    "MonthsBetweenRebalancing": 12,
    "RebalancingThreshold": 0,
    "InflationAdjustedReturns": false
}

=== saturnairjam/PortfolioVisualizer/Data/Portfolios/Classic6040Portfolio.json
{
    "Name": "Classic 60-40 Portfolio",
    "AssetClassWeights":
    [
        ["NIFTY 50 Total Returns Index", 60],
        ["CRISIL Liquid Fund Index", 40]
    ],
    "RebalancingStrategy": "Periodic",
    "MonthsBetweenRebalancing": 12,
    "RebalancingThreshold": 0,
    "InflationAdjustedReturns": false
}

=== saturnairjam/PortfolioVisualizer/Data/Portfolios/TriadPortfolio.json
{
    "Name": "Triad Portfolio",
    "AssetClassWeights":
    [
        ["NIFTY 50 Total Returns Index", 10],
        ["CRISIL Liquid Fund Index", 10],
        ["Gold Price Per Troy Oz", 10]
    ],
    "RebalancingStrategy": "Periodic",
    "MonthsBetweenRebalancing": 12,
    "RebalancingThreshold": 0,
    "InflationAdjustedReturns": false
}
